desc 'refine html'
task :refine_html do
  require 'nokogiri'

  Dir.glob('../_site/*.html').each do |path|
    file = File.open(path)
    file_name = File.basename(path, ".*")
    html = Nokogiri::HTML(file, nil, 'utf-8')

    html.css('#home .posts a').each do |a|
      href = a.attr('href')
      a.attributes['href'].value = href.gsub!('-','_') # Change to support RailsTutorialJP naming style
    end

    file_name.gsub!('-','_') # Change to support RailsTutorialJP naming style

    refine_path = "../_site/#{file_name}_refinement.html"
    File.open(refine_path, 'w+') { |f| f.write(html) }
  end
end
